[package]
name = "nescrow"
version = "1.0.0"
authors = ["volodymyr.matselyukh@gmail.com"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "5.1.0"
borsh = "1.5.1"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[workspace]
members = []

